fix: envrcd not working

diff --git a/release b/release
--- a/release
+++ b/release
@@ -5,22 +5,28 @@ set -TCEeuo pipefail # Strict Bash
 # It's mandatory because the tag version is in the .pre-commit-config.yaml tag file
 # so we need to update it
 
-bump_type=${1:-"patch"}  # or minor, major
+bump_type=${1:-"patch"} # or minor, major
 # Get the tags locally
 git pull
 # calculate the next version
 export GIT_CLIFF__BUMP__INITIAL_TAG=v0.1.0 # by default it's 0.1.0
-next_version=$(git cliff --unreleased --bump "$bump_type" --context  --tag-pattern "v[0-9]+\\.[0-9]+\\.[0-9]+" | jq -r '.[0].version' | tr -d "v")
+next_version=$(git cliff --unreleased --bump "$bump_type" --context --tag-pattern "v[0-9]+\\.[0-9]+\\.[0-9]+" | jq -r '.[0].version' | tr -d "v")
+echo "New version: $next_version"
 
 # Update in-place the version
 # We patch to keep style formatting
+echo "Updating copier.yml project version"
 ORIGIN_NORMALIZED_COPIER=/tmp/copier-origin.yml
 NEW_NORMALIZED_COPIER=/tmp/copier-new.yml
 PATCH_COPIER=/tmp/copier-patch.yml.diff
-yq --exit-status . copier.yml > "$ORIGIN_NORMALIZED_COPIER"
-yq --exit-status "(._external_data.project_version) = \"v$next_version\"" copier.yml > "$NEW_NORMALIZED_COPIER"
-diff "$ORIGIN_NORMALIZED_COPIER" "$NEW_NORMALIZED_COPIER" > "$PATCH_COPIER"
+yq --exit-status . copier.yml >"$ORIGIN_NORMALIZED_COPIER"
+yq --exit-status "(._external_data.project_version) = \"v$next_version\"" copier.yml >"$NEW_NORMALIZED_COPIER"
+diff "$ORIGIN_NORMALIZED_COPIER" "$NEW_NORMALIZED_COPIER" >"$PATCH_COPIER"
 patch copier.yml "$PATCH_COPIER"
+if ! grep -q "project_version: \"v$next_version\"" copier.yml; then
+  echo "Update failed"
+  exit 1
+fi
 
 # Commit
 git-commit "chore: release $next_version"
